#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/gu" install native-image || true
export PATH=$GRAALVM_HOME/bin:$PATH

JAR=target/libhsqldb-0.0.1-SNAPSHOT-standalone.jar
SVM_JAR=$GRAALVM_HOME/jre/lib/svm/builder/svm.jar

lein do clean, uberjar
$GRAALVM_HOME/bin/javac -cp $JAR:$SVM_JAR src/org/babashka/LibHsqlDb.java

$GRAALVM_HOME/bin/native-image \
  -jar $JAR \
  -cp src \
  -H:Name=libhsqldb.babashka.org \
  --shared \
  -H:+ReportExceptionStackTraces \
  -J-Dclojure.spec.skip-macros=true \
  -J-Dclojure.compiler.direct-linking=true \
  "-H:IncludeResources=SCI_VERSION" \
  -H:ReflectionConfigurationFiles=reflection.json \
  --initialize-at-run-time=java.lang.Math\$RandomNumberGeneratorHolder \
  --initialize-at-build-time  \
  -H:Log=registerResource: \
  --verbose \
  --no-fallback \
  --no-server \
  --report-unsupported-elements-at-runtime \
  "-J-Xmx4500m"
