#!/usr/bin/env bb
;; Builds a corpus for the mvn oracle: the top N Clojars artifacts by
;; downloads, at their most downloaded release version, plus a fixed set of
;; Central artifacts at their latest release. Writes corpus-scale.edn.
(require '[babashka.http-client :as http]
         '[clojure.edn :as edn]
         '[clojure.string :as str]
         '[cheshire.core :as json])

(def n (or (some-> (first *command-line-args*) parse-long) 200))
(def out (or (second *command-line-args*) "corpus-scale.edn"))

(defn release? [v]
  (and (not (str/includes? v "SNAPSHOT"))
       (not (re-find #"(?i)alpha|beta|rc|snapshot|milestone|-m\d" v))))

(def clojars-stats
  (edn/read-string (:body (http/get "https://repo.clojars.org/stats/all.edn"))))

(def clojars-top
  (->> clojars-stats
       (map (fn [[[g a] versions]]
              (let [releases (filter (comp release? key) versions)]
                (when (seq releases)
                  (let [[v _] (apply max-key val releases)]
                    {:lib (symbol g a) :version v
                     :downloads (reduce + (vals versions))})))))
       (remove nil?)
       ;; lein plugins and templates are not deps
       (remove #(re-find #"^lein-|/lein-template$|^lein/" (str (:lib %))))
       (sort-by :downloads >)
       (take n)))

(def central-libs
  '[com.fasterxml.jackson.core/jackson-databind com.google.guava/guava
    io.netty/netty-all org.slf4j/slf4j-api ch.qos.logback/logback-classic
    commons-io/commons-io org.apache.commons/commons-lang3
    com.squareup.okhttp3/okhttp com.google.code.gson/gson
    org.postgresql/postgresql com.h2database/h2 com.zaxxer/HikariCP
    org.eclipse.jetty/jetty-server software.amazon.awssdk/s3
    org.jetbrains.kotlin/kotlin-stdlib com.google.protobuf/protobuf-java
    io.grpc/grpc-netty org.bouncycastle/bcprov-jdk18on
    org.apache.lucene/lucene-core org.jsoup/jsoup org.yaml/snakeyaml
    org.junit.jupiter/junit-jupiter org.mockito/mockito-core
    org.hibernate.orm/hibernate-core org.apache.logging.log4j/log4j-core
    io.micrometer/micrometer-core io.opentelemetry/opentelemetry-api
    org.testcontainers/testcontainers org.seleniumhq.selenium/selenium-java
    org.springframework.boot/spring-boot-starter-web
    org.apache.kafka/kafka-clients org.apache.httpcomponents.client5/httpclient5
    com.amazonaws/aws-java-sdk-s3 org.xerial/sqlite-jdbc
    org.mongodb/mongodb-driver-sync redis.clients/jedis
    org.apache.poi/poi-ooxml io.vertx/vertx-core org.apache.spark/spark-core_2.13])

(defn central-latest [lib]
  (let [url (format "https://search.maven.org/solrsearch/select?q=g:%s+AND+a:%s&rows=1&wt=json"
                    (namespace lib) (name lib))
        body (json/parse-string (:body (http/get url {:throw false})) true)]
    (-> body :response :docs first :latestVersion)))

(def central-top
  (doall (for [lib central-libs
               :let [v (try (central-latest lib) (catch Exception _ nil))]
               :when v]
           {:lib lib :version v})))

(defn entry [{:keys [lib version]}]
  {:name (str/replace (str lib) #"[^A-Za-z0-9._-]" "_")
   :deps {lib {:mvn/version version}}})

(let [entries (mapv entry (concat clojars-top central-top))]
  (spit out (with-out-str
              (println ";; generated by build_corpus.clj on" (str (java.time.LocalDate/now)))
              (prn entries)))
  (println (count clojars-top) "clojars," (count central-top) "central ->" out))
