FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y curl \
    && mkdir -p /usr/local/bin

ARG TARGETARCH

COPY ${TARGETARCH}/bb /usr/local/bin/bb

RUN chmod +x /usr/local/bin/bb

CMD ["bb"]
