FROM ubuntu:latest

RUN apt-get update \
    && apt-get install -y curl \
    && mkdir -p /usr/local/bin

ARG TARGETARCH
ARG TARGETOS

COPY metabom.jar /opt/babashka-metabom.jar
COPY ${TARGETOS}/${TARGETARCH}/bb /usr/local/bin/bb

RUN chmod +x /usr/local/bin/bb

CMD ["bb"]
