#!/usr/bin/env bash

cd /tmp
git clone https://github.com/technomancy/leiningen/tree/f3864bc35d8280a8461b7f6c593b1919a75bef7f
sudo mkdir -p /usr/local/bin/
cp leiningen/bin/lein /usr/local/bin
chmod a+x /usr/local/bin/lein
