#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp bb /tmp/release
VERSION=$(cat resources/BABASHKA_VERSION)

cd /tmp/release

## release binary as zip archive

zip "babashka-$VERSION-$BABASHKA_PLATFORM-amd64.zip" bb

## cleanup

rm bb
