#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp bb /tmp/release
# cp src-bash/bbk /tmp/release

VERSION=$(cat resources/BABASHKA_VERSION)

cd /tmp/release
mkdir -p /tmp/bb_size
./bb '(spit "/tmp/bb_size/size" (.length (io/file "bb")))'

## release binary as tar.gz archive

arch=${BABASHKA_ARCH:-amd64}

if [ "$BABASHKA_STATIC" = "true" ]; then
    arch="$arch-static"
fi

tar zcvf "babashka-$VERSION-$BABASHKA_PLATFORM-$arch.tar.gz" bb # bbk

## cleanup

rm bb # bbk
