(ns babashka.impl.ffi
  {:no-doc true}
  (:require [babashka.ffi :as ffi]
            [sci.core :as sci :refer [copy-var]]))

(def tns (sci/create-ns 'babashka.ffi nil))

(def ffi-namespace
  {'load-library (copy-var ffi/load-library tns)
   'load-system-library (copy-var ffi/load-system-library tns)
   'find-symbol (copy-var ffi/find-symbol tns)
   'cfn (copy-var ffi/cfn tns)
   'defcfn (copy-var ffi/defcfn tns)
   'alloc (copy-var ffi/alloc tns)
   'confined-arena (copy-var ffi/confined-arena tns)
   'shared-arena (copy-var ffi/shared-arena tns)
   'auto-arena (copy-var ffi/auto-arena tns)
   'global-arena (copy-var ffi/global-arena tns)
   'sizeof (copy-var ffi/sizeof tns)
   'alignof (copy-var ffi/alignof tns)
   'read (copy-var ffi/read tns)
   'write (copy-var ffi/write tns)
   'ptr->string (copy-var ffi/ptr->string tns)
   'byte-buffer (copy-var ffi/byte-buffer tns)
   'read-bytes (copy-var ffi/read-bytes tns)
   'write-bytes (copy-var ffi/write-bytes tns)
   'string->ptr (copy-var ffi/string->ptr tns)
   'segment (copy-var ffi/segment tns)
   'reinterpret (copy-var ffi/reinterpret tns)
   'slice (copy-var ffi/slice tns)
   'address (copy-var ffi/address tns)
   'size (copy-var ffi/size tns)
   'pointer? (copy-var ffi/pointer? tns)
   'null (copy-var ffi/null tns)
   'null? (copy-var ffi/null? tns)
   'callback (copy-var ffi/callback tns)})
