;; Generated by script/gen_ffi_metadata.clj. Do not edit.
(ns babashka.impl.ffi-trampolines
  {:no-doc true}
  (:import [babashka.impl FfiTrampoline]))

(def builders
  {
   "V_"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_ fnp ) nil))))

   "J_"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_ fnp ))))

   "D_"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_ fnp ))))

   "F_"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_ fnp ))))

   "V_F"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_F fnp (float (aget a 0))) nil))))

   "J_F"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_F fnp (float (aget a 0))))))

   "D_F"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_F fnp (float (aget a 0))))))

   "F_F"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_F fnp (float (aget a 0))))))

   "V_FF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_FF fnp (float (aget a 0)) (float (aget a 1))) nil))))

   "J_FF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_FF fnp (float (aget a 0)) (float (aget a 1))))))

   "D_FF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_FF fnp (float (aget a 0)) (float (aget a 1))))))

   "F_FF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_FF fnp (float (aget a 0)) (float (aget a 1))))))

   "V_FFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_FFF fnp (float (aget a 0)) (float (aget a 1)) (float (aget a 2))) nil))))

   "J_FFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_FFF fnp (float (aget a 0)) (float (aget a 1)) (float (aget a 2))))))

   "D_FFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_FFF fnp (float (aget a 0)) (float (aget a 1)) (float (aget a 2))))))

   "F_FFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_FFF fnp (float (aget a 0)) (float (aget a 1)) (float (aget a 2))))))

   "V_FFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_FFFF fnp (float (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))) nil))))

   "J_FFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_FFFF fnp (float (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "D_FFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_FFFF fnp (float (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "F_FFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_FFFF fnp (float (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "V_D"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_D fnp (double (aget a 0))) nil))))

   "J_D"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_D fnp (double (aget a 0))))))

   "D_D"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_D fnp (double (aget a 0))))))

   "F_D"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_D fnp (double (aget a 0))))))

   "V_DF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_DF fnp (double (aget a 0)) (float (aget a 1))) nil))))

   "J_DF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_DF fnp (double (aget a 0)) (float (aget a 1))))))

   "D_DF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_DF fnp (double (aget a 0)) (float (aget a 1))))))

   "F_DF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_DF fnp (double (aget a 0)) (float (aget a 1))))))

   "V_DFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_DFF fnp (double (aget a 0)) (float (aget a 1)) (float (aget a 2))) nil))))

   "J_DFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_DFF fnp (double (aget a 0)) (float (aget a 1)) (float (aget a 2))))))

   "D_DFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_DFF fnp (double (aget a 0)) (float (aget a 1)) (float (aget a 2))))))

   "F_DFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_DFF fnp (double (aget a 0)) (float (aget a 1)) (float (aget a 2))))))

   "V_DFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_DFFF fnp (double (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))) nil))))

   "J_DFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_DFFF fnp (double (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "D_DFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_DFFF fnp (double (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "F_DFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_DFFF fnp (double (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "V_DD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_DD fnp (double (aget a 0)) (double (aget a 1))) nil))))

   "J_DD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_DD fnp (double (aget a 0)) (double (aget a 1))))))

   "D_DD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_DD fnp (double (aget a 0)) (double (aget a 1))))))

   "F_DD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_DD fnp (double (aget a 0)) (double (aget a 1))))))

   "V_DDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_DDF fnp (double (aget a 0)) (double (aget a 1)) (float (aget a 2))) nil))))

   "J_DDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_DDF fnp (double (aget a 0)) (double (aget a 1)) (float (aget a 2))))))

   "D_DDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_DDF fnp (double (aget a 0)) (double (aget a 1)) (float (aget a 2))))))

   "F_DDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_DDF fnp (double (aget a 0)) (double (aget a 1)) (float (aget a 2))))))

   "V_DDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_DDFF fnp (double (aget a 0)) (double (aget a 1)) (float (aget a 2)) (float (aget a 3))) nil))))

   "J_DDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_DDFF fnp (double (aget a 0)) (double (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "D_DDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_DDFF fnp (double (aget a 0)) (double (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "F_DDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_DDFF fnp (double (aget a 0)) (double (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "V_DDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_DDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2))) nil))))

   "J_DDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_DDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2))))))

   "D_DDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_DDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2))))))

   "F_DDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_DDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2))))))

   "V_DDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_DDDF fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (float (aget a 3))) nil))))

   "J_DDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_DDDF fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (float (aget a 3))))))

   "D_DDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_DDDF fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (float (aget a 3))))))

   "F_DDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_DDDF fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (float (aget a 3))))))

   "V_DDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_DDDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3))) nil))))

   "J_DDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_DDDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3))))))

   "D_DDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_DDDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3))))))

   "F_DDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_DDDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3))))))

   "V_DDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_DDDDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4))) nil))))

   "J_DDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_DDDDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4))))))

   "D_DDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_DDDDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4))))))

   "V_DDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_DDDDDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))) nil))))

   "J_DDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_DDDDDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))))))

   "D_DDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_DDDDDD fnp (double (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))))))

   "V_J"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_J fnp (long (aget a 0))) nil))))

   "J_J"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_J fnp (long (aget a 0))))))

   "D_J"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_J fnp (long (aget a 0))))))

   "F_J"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_J fnp (long (aget a 0))))))

   "V_JF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JF fnp (long (aget a 0)) (float (aget a 1))) nil))))

   "J_JF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JF fnp (long (aget a 0)) (float (aget a 1))))))

   "D_JF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JF fnp (long (aget a 0)) (float (aget a 1))))))

   "F_JF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JF fnp (long (aget a 0)) (float (aget a 1))))))

   "V_JFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JFF fnp (long (aget a 0)) (float (aget a 1)) (float (aget a 2))) nil))))

   "J_JFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JFF fnp (long (aget a 0)) (float (aget a 1)) (float (aget a 2))))))

   "D_JFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JFF fnp (long (aget a 0)) (float (aget a 1)) (float (aget a 2))))))

   "F_JFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JFF fnp (long (aget a 0)) (float (aget a 1)) (float (aget a 2))))))

   "V_JFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JFFF fnp (long (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))) nil))))

   "J_JFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JFFF fnp (long (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "D_JFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JFFF fnp (long (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "F_JFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JFFF fnp (long (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "V_JFFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JFFFF fnp (long (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4))) nil))))

   "J_JFFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JFFFF fnp (long (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "D_JFFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JFFFF fnp (long (aget a 0)) (float (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "V_JD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JD fnp (long (aget a 0)) (double (aget a 1))) nil))))

   "J_JD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JD fnp (long (aget a 0)) (double (aget a 1))))))

   "D_JD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JD fnp (long (aget a 0)) (double (aget a 1))))))

   "F_JD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JD fnp (long (aget a 0)) (double (aget a 1))))))

   "V_JDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JDF fnp (long (aget a 0)) (double (aget a 1)) (float (aget a 2))) nil))))

   "J_JDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JDF fnp (long (aget a 0)) (double (aget a 1)) (float (aget a 2))))))

   "D_JDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JDF fnp (long (aget a 0)) (double (aget a 1)) (float (aget a 2))))))

   "F_JDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JDF fnp (long (aget a 0)) (double (aget a 1)) (float (aget a 2))))))

   "V_JDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JDFF fnp (long (aget a 0)) (double (aget a 1)) (float (aget a 2)) (float (aget a 3))) nil))))

   "J_JDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JDFF fnp (long (aget a 0)) (double (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "D_JDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JDFF fnp (long (aget a 0)) (double (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "F_JDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JDFF fnp (long (aget a 0)) (double (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "V_JDFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JDFFF fnp (long (aget a 0)) (double (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4))) nil))))

   "J_JDFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JDFFF fnp (long (aget a 0)) (double (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "D_JDFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JDFFF fnp (long (aget a 0)) (double (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "V_JDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2))) nil))))

   "J_JDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2))))))

   "D_JDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2))))))

   "F_JDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2))))))

   "V_JDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JDDF fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (float (aget a 3))) nil))))

   "J_JDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JDDF fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (float (aget a 3))))))

   "D_JDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JDDF fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (float (aget a 3))))))

   "F_JDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JDDF fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (float (aget a 3))))))

   "V_JDDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JDDFF fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (float (aget a 3)) (float (aget a 4))) nil))))

   "J_JDDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JDDFF fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "D_JDDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JDDFF fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "V_JDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3))) nil))))

   "J_JDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3))))))

   "D_JDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3))))))

   "F_JDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3))))))

   "V_JDDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JDDDF fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (float (aget a 4))) nil))))

   "J_JDDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JDDDF fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (float (aget a 4))))))

   "D_JDDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JDDDF fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (float (aget a 4))))))

   "V_JDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JDDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4))) nil))))

   "J_JDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JDDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4))))))

   "D_JDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JDDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4))))))

   "V_JDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JDDDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))) nil))))

   "J_JDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JDDDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))))))

   "D_JDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JDDDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))))))

   "V_JDDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JDDDDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))) nil))))

   "J_JDDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JDDDDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))))))

   "D_JDDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JDDDDDD fnp (long (aget a 0)) (double (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))))))

   "V_JJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJ fnp (long (aget a 0)) (long (aget a 1))) nil))))

   "J_JJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJ fnp (long (aget a 0)) (long (aget a 1))))))

   "D_JJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJ fnp (long (aget a 0)) (long (aget a 1))))))

   "F_JJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JJ fnp (long (aget a 0)) (long (aget a 1))))))

   "V_JJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2))) nil))))

   "J_JJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2))))))

   "D_JJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2))))))

   "F_JJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JJF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2))))))

   "V_JJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJFF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2)) (float (aget a 3))) nil))))

   "J_JJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJFF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "D_JJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJFF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "F_JJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JJFF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2)) (float (aget a 3))))))

   "V_JJFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJFFF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4))) nil))))

   "J_JJFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJFFF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "D_JJFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJFFF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "V_JJFFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJFFFF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5))) nil))))

   "J_JJFFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJFFFF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "D_JJFFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJFFFF fnp (long (aget a 0)) (long (aget a 1)) (float (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "V_JJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2))) nil))))

   "J_JJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2))))))

   "D_JJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2))))))

   "F_JJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JJD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2))))))

   "V_JJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJDF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (float (aget a 3))) nil))))

   "J_JJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJDF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (float (aget a 3))))))

   "D_JJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJDF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (float (aget a 3))))))

   "F_JJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JJDF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (float (aget a 3))))))

   "V_JJDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJDFF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (float (aget a 3)) (float (aget a 4))) nil))))

   "J_JJDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJDFF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "D_JJDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJDFF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "V_JJDFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJDFFF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5))) nil))))

   "J_JJDFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJDFFF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "D_JJDFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJDFFF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "V_JJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3))) nil))))

   "J_JJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3))))))

   "D_JJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3))))))

   "F_JJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JJDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3))))))

   "V_JJDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJDDF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (float (aget a 4))) nil))))

   "J_JJDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJDDF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (float (aget a 4))))))

   "D_JJDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJDDF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (float (aget a 4))))))

   "V_JJDDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJDDFF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (float (aget a 4)) (float (aget a 5))) nil))))

   "J_JJDDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJDDFF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "D_JJDDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJDDFF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "V_JJDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJDDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4))) nil))))

   "J_JJDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJDDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4))))))

   "D_JJDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJDDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4))))))

   "V_JJDDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJDDDF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (float (aget a 5))) nil))))

   "J_JJDDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJDDDF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (float (aget a 5))))))

   "D_JJDDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJDDDF fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (float (aget a 5))))))

   "V_JJDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJDDDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))) nil))))

   "J_JJDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJDDDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))))))

   "D_JJDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJDDDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))))))

   "V_JJDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJDDDDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))) nil))))

   "J_JJDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJDDDDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))))))

   "D_JJDDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJDDDDD fnp (long (aget a 0)) (long (aget a 1)) (double (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))))))

   "V_JJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2))) nil))))

   "J_JJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2))))))

   "D_JJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2))))))

   "F_JJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2))))))

   "V_JJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3))) nil))))

   "J_JJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3))))))

   "D_JJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3))))))

   "F_JJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3))))))

   "V_JJJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3)) (float (aget a 4))) nil))))

   "J_JJJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "D_JJJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3)) (float (aget a 4))))))

   "V_JJJFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5))) nil))))

   "J_JJJFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "D_JJJFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "V_JJJFFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJFFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5)) (float (aget a 6))) nil))))

   "J_JJJFFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJFFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "D_JJJFFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJFFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (float (aget a 3)) (float (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "V_JJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3))) nil))))

   "J_JJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3))))))

   "D_JJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3))))))

   "F_JJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3))))))

   "V_JJJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (float (aget a 4))) nil))))

   "J_JJJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (float (aget a 4))))))

   "D_JJJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (float (aget a 4))))))

   "V_JJJDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJDFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (float (aget a 4)) (float (aget a 5))) nil))))

   "J_JJJDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJDFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "D_JJJDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJDFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "V_JJJDFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJDFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (float (aget a 4)) (float (aget a 5)) (float (aget a 6))) nil))))

   "J_JJJDFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJDFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (float (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "D_JJJDFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJDFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (float (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "V_JJJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4))) nil))))

   "J_JJJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4))))))

   "D_JJJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4))))))

   "V_JJJDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJDDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (float (aget a 5))) nil))))

   "J_JJJDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJDDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (float (aget a 5))))))

   "D_JJJDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJDDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (float (aget a 5))))))

   "V_JJJDDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJDDFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (float (aget a 5)) (float (aget a 6))) nil))))

   "J_JJJDDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJDDFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "D_JJJDDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJDDFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "V_JJJDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJDDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))) nil))))

   "J_JJJDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJDDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))))))

   "D_JJJDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJDDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5))))))

   "V_JJJDDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJDDDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (float (aget a 6))) nil))))

   "J_JJJDDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJDDDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (float (aget a 6))))))

   "D_JJJDDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJDDDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (float (aget a 6))))))

   "V_JJJDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJDDDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))) nil))))

   "J_JJJDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJDDDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))))))

   "D_JJJDDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJDDDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (double (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))))))

   "V_JJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3))) nil))))

   "J_JJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3))))))

   "D_JJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3))))))

   "F_JJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callF_JJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3))))))

   "V_JJJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (float (aget a 4))) nil))))

   "J_JJJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (float (aget a 4))))))

   "D_JJJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (float (aget a 4))))))

   "V_JJJJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (float (aget a 4)) (float (aget a 5))) nil))))

   "J_JJJJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "D_JJJJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (float (aget a 4)) (float (aget a 5))))))

   "V_JJJJFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (float (aget a 4)) (float (aget a 5)) (float (aget a 6))) nil))))

   "J_JJJJFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (float (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "D_JJJJFFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJFFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (float (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "V_JJJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4))) nil))))

   "J_JJJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4))))))

   "D_JJJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4))))))

   "V_JJJJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (float (aget a 5))) nil))))

   "J_JJJJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (float (aget a 5))))))

   "D_JJJJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (float (aget a 5))))))

   "V_JJJJDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJDFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (float (aget a 5)) (float (aget a 6))) nil))))

   "J_JJJJDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJDFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "D_JJJJDFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJDFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "V_JJJJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (double (aget a 5))) nil))))

   "J_JJJJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (double (aget a 5))))))

   "D_JJJJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (double (aget a 5))))))

   "V_JJJJDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJDDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (double (aget a 5)) (float (aget a 6))) nil))))

   "J_JJJJDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJDDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (double (aget a 5)) (float (aget a 6))))))

   "D_JJJJDDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJDDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (double (aget a 5)) (float (aget a 6))))))

   "V_JJJJDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJDDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))) nil))))

   "J_JJJJDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJDDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))))))

   "D_JJJJDDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJDDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (double (aget a 4)) (double (aget a 5)) (double (aget a 6))))))

   "V_JJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4))) nil))))

   "J_JJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4))))))

   "D_JJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4))))))

   "V_JJJJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (float (aget a 5))) nil))))

   "J_JJJJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (float (aget a 5))))))

   "D_JJJJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (float (aget a 5))))))

   "V_JJJJJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (float (aget a 5)) (float (aget a 6))) nil))))

   "J_JJJJJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "D_JJJJJFF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJFF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (float (aget a 5)) (float (aget a 6))))))

   "V_JJJJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (double (aget a 5))) nil))))

   "J_JJJJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (double (aget a 5))))))

   "D_JJJJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (double (aget a 5))))))

   "V_JJJJJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (double (aget a 5)) (float (aget a 6))) nil))))

   "J_JJJJJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (double (aget a 5)) (float (aget a 6))))))

   "D_JJJJJDF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJDF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (double (aget a 5)) (float (aget a 6))))))

   "V_JJJJJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (double (aget a 5)) (double (aget a 6))) nil))))

   "J_JJJJJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (double (aget a 5)) (double (aget a 6))))))

   "D_JJJJJDD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJDD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (double (aget a 5)) (double (aget a 6))))))

   "V_JJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5))) nil))))

   "J_JJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5))))))

   "D_JJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5))))))

   "V_JJJJJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (float (aget a 6))) nil))))

   "J_JJJJJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (float (aget a 6))))))

   "D_JJJJJJF"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJJF fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (float (aget a 6))))))

   "V_JJJJJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (double (aget a 6))) nil))))

   "J_JJJJJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (double (aget a 6))))))

   "D_JJJJJJD"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJJD fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (double (aget a 6))))))

   "V_JJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6))) nil))))

   "J_JJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6))))))

   "D_JJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6))))))

   "V_JJJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6)) (long (aget a 7))) nil))))

   "J_JJJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6)) (long (aget a 7))))))

   "D_JJJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6)) (long (aget a 7))))))

   "V_JJJJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6)) (long (aget a 7)) (long (aget a 8))) nil))))

   "J_JJJJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6)) (long (aget a 7)) (long (aget a 8))))))

   "D_JJJJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6)) (long (aget a 7)) (long (aget a 8))))))

   "V_JJJJJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (do (FfiTrampoline/callV_JJJJJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6)) (long (aget a 7)) (long (aget a 8)) (long (aget a 9))) nil))))

   "J_JJJJJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callJ_JJJJJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6)) (long (aget a 7)) (long (aget a 8)) (long (aget a 9))))))

   "D_JJJJJJJJJJ"
   (fn [fnp]
     (let [fnp (long fnp)]
       (fn [^objects a]
         (FfiTrampoline/callD_JJJJJJJJJJ fnp (long (aget a 0)) (long (aget a 1)) (long (aget a 2)) (long (aget a 3)) (long (aget a 4)) (long (aget a 5)) (long (aget a 6)) (long (aget a 7)) (long (aget a 8)) (long (aget a 9))))))
   })
