#!/usr/bin/env bash

set -euo pipefail

GRAALVM_VERSION="${GRAALVM_VERSION:-21.2.0}"

case "$BABASHKA_PLATFORM" in
	macos)
		GRAALVM_PLATFORM="darwin"
		;;
	linux)
		GRAALVM_PLATFORM="linux"
		;;
	*)
		echo "Invalid platform $BABASHKA_PLATFORM!" >&2
		exit 1
		;;
esac

case "$BABASHKA_ARCH" in
	amd64)
		GRAALVM_ARCH="amd64"
		;;
	aarch64)
		GRAALVM_ARCH="aarch64"
		;;
	*)
		echo "Invalid arch $BABASHKA_ARCH!" >&2
		exit 1
		;;
esac

if ! [ -d "graalvm-ce-java11-$GRAALVM_VERSION" ]; then
	echo "Downloading GraalVM $GRAALVM_PLATFORM-$GRAALVM_ARCH-$GRAALVM_VERSION on '$PWD'..."
	curl -O -sL "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java11-$GRAALVM_PLATFORM-$GRAALVM_ARCH-$GRAALVM_VERSION.tar.gz"
	tar xzf graalvm-ce-java11-$GRAALVM_PLATFORM-$GRAALVM_ARCH-$GRAALVM_VERSION.tar.gz
fi
