#!/usr/bin/env bash

docker run --name babashka-postgres -p 54322:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres

if [ "$BABASHKA_TEST_ENV" = "native" ]; then
    BB_CMD="./bb"
else
    BB_CMD="lein bb"
fi

"$BB_CMD" -f test-resources/babashka/postgres_test.clj

docker rm -f babashka-postgres
