#!/usr/bin/env bash

set -eo pipefail

if [ "$GRAALVM_HOME" != "" ]
then
    export JAVA_HOME=$GRAALVM_HOME
    export PATH=$GRAALVM_HOME/bin:$PATH
fi

script/lib_tests/clj_http_lite_test
script/lib_tests/deps_clj_test
script/lib_tests/spartan_spec_test
script/lib_tests/clojure_csv_test
script/lib_tests/regal_test
script/lib_tests/medley_test
script/lib_tests/babashka_curl_test
script/lib_tests/cprop_test
script/lib_tests/comb_test
script/lib_tests/arrangement_test
script/lib_tests/clj_yaml_test
script/lib_tests/clojure_data_csv_test
script/lib_tests/combinatorics_test
script/lib_tests/doric_test
script/lib_tests/clojure_data_zip_test
script/lib_tests/cljc_java_time_test
