#!/usr/bin/env bash

set -eo pipefail

if [ "$JET_TEST_ENV" = "native" ]; then
    lein test
else
    echo "Testing with Clojure 1.9.0"
    lein with-profiles +clojure-1.9.0 test

    echo "Testing with Clojure 1.10.1"
    lein with-profiles +clojure-1.10.1 test
fi
