#!/usr/bin/env bash

if [ "$GRAALVM_HOME" != "" ]
then
    export JAVA_HOME=$GRAALVM_HOME
    export PATH=$GRAALVM_HOME/bin:$PATH
fi

java -version

set -eo pipefail

if [ "$BABASHKA_LEAN" = "true" ]
then
    export BABASHKA_FEATURE_JDBC=false
    export BABASHKA_FEATURE_POSTGRESQL=false
    export BABASHKA_FEATURE_HSQLDB=false
    export BABASHKA_FEATURE_XML=false
    export BABASHKA_FEATURE_YAML=false
    export BABASHKA_FEATURE_CORE_ASYNC=false
    export BABASHKA_FEATURE_CSV=false
    export BABAHSKA_FEATURE_TRANSIT=false
    export BABASHKA_FEATURE_JAVA_TIME=false
    export BABASHKA_FEATURE_JAVA_NIO=false
fi

BABASHKA_LEIN_PROFILES="+uberjar"

if [ "$BABASHKA_FEATURE_JDBC" = "true" ]
then
    BABASHKA_LEIN_PROFILES+=",+feature/jdbc"
else
    BABASHKA_LEIN_PROFILES+=",-feature/jdbc"
fi

if [ "$BABASHKA_FEATURE_POSTGRESQL" = "true" ]
then
    BABASHKA_LEIN_PROFILES+=",+feature/postgresql"
else
    BABASHKA_LEIN_PROFILES+=",-feature/postgresql"
fi

if [ "$BABASHKA_FEATURE_HSQLDB" = "true" ]
then
    BABASHKA_LEIN_PROFILES+=",+feature/hsqldb"
else
    BABASHKA_LEIN_PROFILES+=",-feature/hsqldb"
fi

if [ "$BABASHKA_FEATURE_XML" != "false" ]
then
    BABASHKA_LEIN_PROFILES+=",+feature/xml"
else
    BABASHKA_LEIN_PROFILES+=",-feature/xml"
fi

if [ "$BABASHKA_FEATURE_YAML" != "false" ]
then
    BABASHKA_LEIN_PROFILES+=",+feature/yaml"
else
    BABASHKA_LEIN_PROFILES+=",-feature/yaml"
fi

if [ "$BABASHKA_FEATURE_CORE_ASYNC" != "false" ]
then
    BABASHKA_LEIN_PROFILES+=",+feature/core-async"
else
    BABASHKA_LEIN_PROFILES+=",-feature/core-async"
fi

if [ "$BABASHKA_FEATURE_CSV" != "false" ]
then
    BABASHKA_LEIN_PROFILES+=",+feature/csv"
else
    BABASHKA_LEIN_PROFILES+=",-feature/csv"
fi

if [ "$BABASHKA_FEATURE_TRANSIT" != "false" ]
then
    BABASHKA_LEIN_PROFILES+=",+feature/transit"
else
    BABASHKA_LEIN_PROFILES+=",-feature/transit"
fi

if [ "$BABASHKA_FEATURE_DATASCRIPT" = "true" ]
then
    BABASHKA_LEIN_PROFILES+=",+feature/datascript"
else
    BABASHKA_LEIN_PROFILES+=",-feature/datascript"
fi

if [ -z "$BABASHKA_JAR" ]; then
    lein with-profiles "$BABASHKA_LEIN_PROFILES,+reflection,-uberjar" do run
    lein with-profiles "$BABASHKA_LEIN_PROFILES" do clean, uberjar
fi
