#!/usr/bin/env bash

set -eo pipefail

export BABASHKA_CLASSPATH=$(clojure -Sdeps '{:deps {babasha.curl {:git/url "https://github.com/borkdude/babashka.curl" :sha "6a4de335fa0ba75814567e013a286cafcabff8c0"}}}' -Spath)

if [ "$BABASHKA_TEST_ENV" = "native" ]; then
    BB_CMD="./bb"
else
    BB_CMD="lein bb"
fi

$BB_CMD -e "
(require '[babashka.curl :as curl] :reload-all)

(prn (:status (curl/get \"https://www.clojure.org\")))

(prn (:status (curl/get \"https://postman-echo.com/get?foo1=bar1&foo2=bar2\")))

(prn (:status (curl/post \"https://postman-echo.com/post\")))

(prn (:status (curl/post \"https://postman-echo.com/post\"
                 {:body (json/generate-string {:a 1})
                 :headers {\"X-Hasura-Role\" \"admin\"}
                 :content-type :json
                 :accept :json})))

(prn (:status (curl/put \"https://postman-echo.com/put\"
                          {:body (json/generate-string {:a 1})
                 :headers {\"X-Hasura-Role\" \"admin\"}
                 :content-type :json
                 :accept :json})))
"
