#!/usr/bin/env bash

set -eo pipefail

export BABASHKA_CLASSPATH="$(clojure -Sdeps '{:deps {clojure-csv {:mvn/version "RELEASE"}}}' -Spath)"

./bb -e "
(require '[clojure-csv.core :as csv])
(prn (csv/write-csv (csv/parse-csv \"a,b,c\n1,2,3\")))
"
