#!/usr/bin/env bash

set -eo pipefail

export BABASHKA_CLASSPATH
BABASHKA_CLASSPATH="$(clojure -Spath -Sdeps '{:deps {doric {:mvn/version "0.9.0"}}}')"

if [ "$BABASHKA_TEST_ENV" = "native" ]; then
    BB_CMD="./bb"
else
    BB_CMD="lein bb"
fi

$BB_CMD -cp "$BABASHKA_CLASSPATH:test-resources/lib_tests" -e "
(require '[doric.test.core])
(require '[clojure.test :as t])
(let [{:keys [:test :pass :fail :error]} (t/run-tests 'doric.test.core)]
  (when-not (pos? test)
    (System/exit 1))
  (System/exit (+ fail error)))
"
