#!/usr/bin/env bash

set -eo pipefail

export BABASHKA_CLASSPATH="$(clojure -Sdeps '{:deps {regal {:git/url "https://github.com/lambdaisland/regal" :sha "b059fdb06d5586a9a04c27e7b011c467ad8546db"}}}' -Spath)"

if [ "$BABASHKA_TEST_ENV" = "native" ]; then
    BB_CMD="./bb"
else
    BB_CMD="lein bb"
fi

$BB_CMD "
(require '[lambdaisland.regal :as regal])
(def r [:cat
        [:+ [:class [\a \z]]]
        \"=\"
        [:+ [:not \=]]])

(prn (regal/regex r))
(prn (re-matches (regal/regex r) \"foo=bar\"))
"
