#!/usr/bin/env bash

set -eo pipefail

export BABASHKA_CLASSPATH="$(clojure -Sdeps '{:deps {regal {:git/url "https://github.com/lambdaisland/regal" :sha "e179f20a2ec78d47c8c24257e644ac80a70e33cb"}}}' -Spath)"

if [ "$BABASHKA_TEST_ENV" = "native" ]; then
    BB_CMD="./bb"
else
    BB_CMD="lein bb"
fi

$BB_CMD "(require '[lambdaisland.regal :as re]) (re/regex [:range \a \z])"
