#!/usr/bin/env bash

set -eo pipefail

if [ "$BABASHKA_TEST_ENV" = "native" ]; then
    BB_CMD="./bb"
else
    BB_CMD="lein bb"
fi

export BABASHKA_CLASSPATH
BABASHKA_CLASSPATH=$(clojure -A:lib-tests -Spath)

$BB_CMD -cp "$BABASHKA_CLASSPATH" \
        -f "test-resources/lib_tests/babashka/run_all_libtests.clj" "$@"
