// Generated by script/gen_ffi_metadata.clj. Do not edit.
package babashka.impl;

import org.graalvm.nativeimage.c.function.CFunctionPointer;
import org.graalvm.nativeimage.c.function.InvokeCFunctionPointer;
import org.graalvm.word.WordFactory;

/** Native-image call trampolines for babashka.ffi: one compiled
 * direct call per canonical shape, dispatched by shape id. Only
 * functional in a native image; never invoked on the JVM. */
public final class FfiTrampoline {
    private FfiTrampoline() {}

    private static long longV(Object o) { return ((Number) o).longValue(); }
    private static double dblV(Object o) { return ((Number) o).doubleValue(); }
    private static float fltV(Object o) { return ((Number) o).floatValue(); }

    public interface F_V_ extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke();
    }

    public interface F_J_ extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke();
    }

    public interface F_D_ extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke();
    }

    public interface F_F_ extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke();
    }

    public interface F_V_D extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(double a0);
    }

    public interface F_J_D extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(double a0);
    }

    public interface F_D_D extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(double a0);
    }

    public interface F_F_D extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(double a0);
    }

    public interface F_V_F extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(float a0);
    }

    public interface F_J_F extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(float a0);
    }

    public interface F_D_F extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(float a0);
    }

    public interface F_F_F extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(float a0);
    }

    public interface F_V_DD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(double a0, double a1);
    }

    public interface F_J_DD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(double a0, double a1);
    }

    public interface F_D_DD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(double a0, double a1);
    }

    public interface F_F_DD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(double a0, double a1);
    }

    public interface F_V_DF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(double a0, float a1);
    }

    public interface F_J_DF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(double a0, float a1);
    }

    public interface F_D_DF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(double a0, float a1);
    }

    public interface F_F_DF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(double a0, float a1);
    }

    public interface F_V_FD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(float a0, double a1);
    }

    public interface F_J_FD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(float a0, double a1);
    }

    public interface F_D_FD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(float a0, double a1);
    }

    public interface F_F_FD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(float a0, double a1);
    }

    public interface F_V_FF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(float a0, float a1);
    }

    public interface F_J_FF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(float a0, float a1);
    }

    public interface F_D_FF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(float a0, float a1);
    }

    public interface F_F_FF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(float a0, float a1);
    }

    public interface F_V_DDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(double a0, double a1, double a2);
    }

    public interface F_J_DDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(double a0, double a1, double a2);
    }

    public interface F_D_DDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(double a0, double a1, double a2);
    }

    public interface F_F_DDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(double a0, double a1, double a2);
    }

    public interface F_V_DDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(double a0, double a1, float a2);
    }

    public interface F_J_DDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(double a0, double a1, float a2);
    }

    public interface F_D_DDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(double a0, double a1, float a2);
    }

    public interface F_F_DDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(double a0, double a1, float a2);
    }

    public interface F_V_DFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(double a0, float a1, double a2);
    }

    public interface F_J_DFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(double a0, float a1, double a2);
    }

    public interface F_D_DFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(double a0, float a1, double a2);
    }

    public interface F_F_DFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(double a0, float a1, double a2);
    }

    public interface F_V_DFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(double a0, float a1, float a2);
    }

    public interface F_J_DFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(double a0, float a1, float a2);
    }

    public interface F_D_DFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(double a0, float a1, float a2);
    }

    public interface F_F_DFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(double a0, float a1, float a2);
    }

    public interface F_V_FDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(float a0, double a1, double a2);
    }

    public interface F_J_FDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(float a0, double a1, double a2);
    }

    public interface F_D_FDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(float a0, double a1, double a2);
    }

    public interface F_F_FDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(float a0, double a1, double a2);
    }

    public interface F_V_FDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(float a0, double a1, float a2);
    }

    public interface F_J_FDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(float a0, double a1, float a2);
    }

    public interface F_D_FDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(float a0, double a1, float a2);
    }

    public interface F_F_FDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(float a0, double a1, float a2);
    }

    public interface F_V_FFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(float a0, float a1, double a2);
    }

    public interface F_J_FFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(float a0, float a1, double a2);
    }

    public interface F_D_FFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(float a0, float a1, double a2);
    }

    public interface F_F_FFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(float a0, float a1, double a2);
    }

    public interface F_V_FFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(float a0, float a1, float a2);
    }

    public interface F_J_FFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(float a0, float a1, float a2);
    }

    public interface F_D_FFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(float a0, float a1, float a2);
    }

    public interface F_F_FFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(float a0, float a1, float a2);
    }

    public interface F_V_FFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(float a0, float a1, float a2, float a3);
    }

    public interface F_J_FFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(float a0, float a1, float a2, float a3);
    }

    public interface F_D_FFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(float a0, float a1, float a2, float a3);
    }

    public interface F_F_FFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(float a0, float a1, float a2, float a3);
    }

    public interface F_V_DDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(double a0, double a1, double a2, double a3);
    }

    public interface F_J_DDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(double a0, double a1, double a2, double a3);
    }

    public interface F_D_DDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(double a0, double a1, double a2, double a3);
    }

    public interface F_F_DDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(double a0, double a1, double a2, double a3);
    }

    public interface F_V_J extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0);
    }

    public interface F_J_J extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0);
    }

    public interface F_D_J extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0);
    }

    public interface F_F_J extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0);
    }

    public interface F_V_JD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, double a1);
    }

    public interface F_J_JD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, double a1);
    }

    public interface F_D_JD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, double a1);
    }

    public interface F_F_JD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, double a1);
    }

    public interface F_V_JF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, float a1);
    }

    public interface F_J_JF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, float a1);
    }

    public interface F_D_JF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, float a1);
    }

    public interface F_F_JF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, float a1);
    }

    public interface F_V_JDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, double a1, double a2);
    }

    public interface F_J_JDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, double a1, double a2);
    }

    public interface F_D_JDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, double a1, double a2);
    }

    public interface F_F_JDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, double a1, double a2);
    }

    public interface F_V_JDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, double a1, float a2);
    }

    public interface F_J_JDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, double a1, float a2);
    }

    public interface F_D_JDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, double a1, float a2);
    }

    public interface F_F_JDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, double a1, float a2);
    }

    public interface F_V_JFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, float a1, double a2);
    }

    public interface F_J_JFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, float a1, double a2);
    }

    public interface F_D_JFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, float a1, double a2);
    }

    public interface F_F_JFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, float a1, double a2);
    }

    public interface F_V_JFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, float a1, float a2);
    }

    public interface F_J_JFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, float a1, float a2);
    }

    public interface F_D_JFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, float a1, float a2);
    }

    public interface F_F_JFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, float a1, float a2);
    }

    public interface F_V_JDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, double a1, double a2, double a3);
    }

    public interface F_J_JDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, double a1, double a2, double a3);
    }

    public interface F_D_JDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, double a1, double a2, double a3);
    }

    public interface F_F_JDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, double a1, double a2, double a3);
    }

    public interface F_V_JDDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, double a1, double a2, float a3);
    }

    public interface F_J_JDDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, double a1, double a2, float a3);
    }

    public interface F_D_JDDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, double a1, double a2, float a3);
    }

    public interface F_F_JDDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, double a1, double a2, float a3);
    }

    public interface F_V_JDFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, double a1, float a2, double a3);
    }

    public interface F_J_JDFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, double a1, float a2, double a3);
    }

    public interface F_D_JDFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, double a1, float a2, double a3);
    }

    public interface F_F_JDFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, double a1, float a2, double a3);
    }

    public interface F_V_JDFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, double a1, float a2, float a3);
    }

    public interface F_J_JDFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, double a1, float a2, float a3);
    }

    public interface F_D_JDFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, double a1, float a2, float a3);
    }

    public interface F_F_JDFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, double a1, float a2, float a3);
    }

    public interface F_V_JFDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, float a1, double a2, double a3);
    }

    public interface F_J_JFDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, float a1, double a2, double a3);
    }

    public interface F_D_JFDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, float a1, double a2, double a3);
    }

    public interface F_F_JFDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, float a1, double a2, double a3);
    }

    public interface F_V_JFDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, float a1, double a2, float a3);
    }

    public interface F_J_JFDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, float a1, double a2, float a3);
    }

    public interface F_D_JFDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, float a1, double a2, float a3);
    }

    public interface F_F_JFDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, float a1, double a2, float a3);
    }

    public interface F_V_JFFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, float a1, float a2, double a3);
    }

    public interface F_J_JFFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, float a1, float a2, double a3);
    }

    public interface F_D_JFFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, float a1, float a2, double a3);
    }

    public interface F_F_JFFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, float a1, float a2, double a3);
    }

    public interface F_V_JFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, float a1, float a2, float a3);
    }

    public interface F_J_JFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, float a1, float a2, float a3);
    }

    public interface F_D_JFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, float a1, float a2, float a3);
    }

    public interface F_F_JFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, float a1, float a2, float a3);
    }

    public interface F_V_JFFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, float a1, float a2, float a3, float a4);
    }

    public interface F_J_JFFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, float a1, float a2, float a3, float a4);
    }

    public interface F_D_JFFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, float a1, float a2, float a3, float a4);
    }

    public interface F_V_JDDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, double a1, double a2, double a3, double a4);
    }

    public interface F_J_JDDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, double a1, double a2, double a3, double a4);
    }

    public interface F_D_JDDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, double a1, double a2, double a3, double a4);
    }

    public interface F_V_JJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1);
    }

    public interface F_J_JJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1);
    }

    public interface F_D_JJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1);
    }

    public interface F_F_JJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, long a1);
    }

    public interface F_V_JJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, double a2);
    }

    public interface F_J_JJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, double a2);
    }

    public interface F_D_JJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, double a2);
    }

    public interface F_F_JJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, long a1, double a2);
    }

    public interface F_V_JJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, float a2);
    }

    public interface F_J_JJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, float a2);
    }

    public interface F_D_JJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, float a2);
    }

    public interface F_F_JJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, long a1, float a2);
    }

    public interface F_V_JJDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, double a2, double a3);
    }

    public interface F_J_JJDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, double a2, double a3);
    }

    public interface F_D_JJDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, double a2, double a3);
    }

    public interface F_F_JJDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, long a1, double a2, double a3);
    }

    public interface F_V_JJDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, double a2, float a3);
    }

    public interface F_J_JJDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, double a2, float a3);
    }

    public interface F_D_JJDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, double a2, float a3);
    }

    public interface F_F_JJDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, long a1, double a2, float a3);
    }

    public interface F_V_JJFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, float a2, double a3);
    }

    public interface F_J_JJFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, float a2, double a3);
    }

    public interface F_D_JJFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, float a2, double a3);
    }

    public interface F_F_JJFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, long a1, float a2, double a3);
    }

    public interface F_V_JJFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, float a2, float a3);
    }

    public interface F_J_JJFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, float a2, float a3);
    }

    public interface F_D_JJFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, float a2, float a3);
    }

    public interface F_F_JJFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, long a1, float a2, float a3);
    }

    public interface F_V_JJDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, double a2, double a3, double a4);
    }

    public interface F_J_JJDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, double a2, double a3, double a4);
    }

    public interface F_D_JJDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, double a2, double a3, double a4);
    }

    public interface F_V_JJDDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, double a2, double a3, float a4);
    }

    public interface F_J_JJDDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, double a2, double a3, float a4);
    }

    public interface F_D_JJDDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, double a2, double a3, float a4);
    }

    public interface F_V_JJDFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, double a2, float a3, double a4);
    }

    public interface F_J_JJDFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, double a2, float a3, double a4);
    }

    public interface F_D_JJDFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, double a2, float a3, double a4);
    }

    public interface F_V_JJDFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, double a2, float a3, float a4);
    }

    public interface F_J_JJDFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, double a2, float a3, float a4);
    }

    public interface F_D_JJDFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, double a2, float a3, float a4);
    }

    public interface F_V_JJFDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, float a2, double a3, double a4);
    }

    public interface F_J_JJFDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, float a2, double a3, double a4);
    }

    public interface F_D_JJFDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, float a2, double a3, double a4);
    }

    public interface F_V_JJFDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, float a2, double a3, float a4);
    }

    public interface F_J_JJFDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, float a2, double a3, float a4);
    }

    public interface F_D_JJFDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, float a2, double a3, float a4);
    }

    public interface F_V_JJFFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, float a2, float a3, double a4);
    }

    public interface F_J_JJFFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, float a2, float a3, double a4);
    }

    public interface F_D_JJFFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, float a2, float a3, double a4);
    }

    public interface F_V_JJFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, float a2, float a3, float a4);
    }

    public interface F_J_JJFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, float a2, float a3, float a4);
    }

    public interface F_D_JJFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, float a2, float a3, float a4);
    }

    public interface F_V_JJFFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, float a2, float a3, float a4, float a5);
    }

    public interface F_J_JJFFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, float a2, float a3, float a4, float a5);
    }

    public interface F_D_JJFFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, float a2, float a3, float a4, float a5);
    }

    public interface F_V_JJDDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, double a2, double a3, double a4, double a5);
    }

    public interface F_J_JJDDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, double a2, double a3, double a4, double a5);
    }

    public interface F_D_JJDDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, double a2, double a3, double a4, double a5);
    }

    public interface F_V_JJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2);
    }

    public interface F_J_JJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2);
    }

    public interface F_D_JJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2);
    }

    public interface F_F_JJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, long a1, long a2);
    }

    public interface F_V_JJJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, double a3);
    }

    public interface F_J_JJJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, double a3);
    }

    public interface F_D_JJJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, double a3);
    }

    public interface F_F_JJJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, long a1, long a2, double a3);
    }

    public interface F_V_JJJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, float a3);
    }

    public interface F_J_JJJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, float a3);
    }

    public interface F_D_JJJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, float a3);
    }

    public interface F_F_JJJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, long a1, long a2, float a3);
    }

    public interface F_V_JJJDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, double a3, double a4);
    }

    public interface F_J_JJJDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, double a3, double a4);
    }

    public interface F_D_JJJDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, double a3, double a4);
    }

    public interface F_V_JJJDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, double a3, float a4);
    }

    public interface F_J_JJJDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, double a3, float a4);
    }

    public interface F_D_JJJDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, double a3, float a4);
    }

    public interface F_V_JJJFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, float a3, double a4);
    }

    public interface F_J_JJJFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, float a3, double a4);
    }

    public interface F_D_JJJFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, float a3, double a4);
    }

    public interface F_V_JJJFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, float a3, float a4);
    }

    public interface F_J_JJJFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, float a3, float a4);
    }

    public interface F_D_JJJFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, float a3, float a4);
    }

    public interface F_V_JJJDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, double a3, double a4, double a5);
    }

    public interface F_J_JJJDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, double a3, double a4, double a5);
    }

    public interface F_D_JJJDDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, double a3, double a4, double a5);
    }

    public interface F_V_JJJDDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, double a3, double a4, float a5);
    }

    public interface F_J_JJJDDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, double a3, double a4, float a5);
    }

    public interface F_D_JJJDDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, double a3, double a4, float a5);
    }

    public interface F_V_JJJDFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, double a3, float a4, double a5);
    }

    public interface F_J_JJJDFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, double a3, float a4, double a5);
    }

    public interface F_D_JJJDFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, double a3, float a4, double a5);
    }

    public interface F_V_JJJDFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, double a3, float a4, float a5);
    }

    public interface F_J_JJJDFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, double a3, float a4, float a5);
    }

    public interface F_D_JJJDFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, double a3, float a4, float a5);
    }

    public interface F_V_JJJFDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, float a3, double a4, double a5);
    }

    public interface F_J_JJJFDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, float a3, double a4, double a5);
    }

    public interface F_D_JJJFDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, float a3, double a4, double a5);
    }

    public interface F_V_JJJFDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, float a3, double a4, float a5);
    }

    public interface F_J_JJJFDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, float a3, double a4, float a5);
    }

    public interface F_D_JJJFDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, float a3, double a4, float a5);
    }

    public interface F_V_JJJFFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, float a3, float a4, double a5);
    }

    public interface F_J_JJJFFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, float a3, float a4, double a5);
    }

    public interface F_D_JJJFFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, float a3, float a4, double a5);
    }

    public interface F_V_JJJFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, float a3, float a4, float a5);
    }

    public interface F_J_JJJFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, float a3, float a4, float a5);
    }

    public interface F_D_JJJFFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, float a3, float a4, float a5);
    }

    public interface F_V_JJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3);
    }

    public interface F_J_JJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3);
    }

    public interface F_D_JJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3);
    }

    public interface F_F_JJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        float invoke(long a0, long a1, long a2, long a3);
    }

    public interface F_V_JJJJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, double a4);
    }

    public interface F_J_JJJJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, double a4);
    }

    public interface F_D_JJJJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, double a4);
    }

    public interface F_V_JJJJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, float a4);
    }

    public interface F_J_JJJJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, float a4);
    }

    public interface F_D_JJJJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, float a4);
    }

    public interface F_V_JJJJDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, double a4, double a5);
    }

    public interface F_J_JJJJDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, double a4, double a5);
    }

    public interface F_D_JJJJDD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, double a4, double a5);
    }

    public interface F_V_JJJJDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, double a4, float a5);
    }

    public interface F_J_JJJJDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, double a4, float a5);
    }

    public interface F_D_JJJJDF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, double a4, float a5);
    }

    public interface F_V_JJJJFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, float a4, double a5);
    }

    public interface F_J_JJJJFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, float a4, double a5);
    }

    public interface F_D_JJJJFD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, float a4, double a5);
    }

    public interface F_V_JJJJFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, float a4, float a5);
    }

    public interface F_J_JJJJFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, float a4, float a5);
    }

    public interface F_D_JJJJFF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, float a4, float a5);
    }

    public interface F_V_JJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, long a4);
    }

    public interface F_J_JJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, long a4);
    }

    public interface F_D_JJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, long a4);
    }

    public interface F_V_JJJJJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, long a4, double a5);
    }

    public interface F_J_JJJJJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, long a4, double a5);
    }

    public interface F_D_JJJJJD extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, long a4, double a5);
    }

    public interface F_V_JJJJJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, long a4, float a5);
    }

    public interface F_J_JJJJJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, long a4, float a5);
    }

    public interface F_D_JJJJJF extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, long a4, float a5);
    }

    public interface F_V_JJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, long a4, long a5);
    }

    public interface F_J_JJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, long a4, long a5);
    }

    public interface F_D_JJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, long a4, long a5);
    }

    public interface F_V_JJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6);
    }

    public interface F_J_JJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6);
    }

    public interface F_D_JJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6);
    }

    public interface F_V_JJJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7);
    }

    public interface F_J_JJJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7);
    }

    public interface F_D_JJJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7);
    }

    public interface F_V_JJJJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8);
    }

    public interface F_J_JJJJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8);
    }

    public interface F_D_JJJJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8);
    }

    public interface F_V_JJJJJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        void invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9);
    }

    public interface F_J_JJJJJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        long invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9);
    }

    public interface F_D_JJJJJJJJJJ extends CFunctionPointer {
        @InvokeCFunctionPointer
        double invoke(long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9);
    }

    public static Object dispatch(int id, long fn, Object[] a) {
        switch (id) {
        case 0: ((F_V_) WordFactory.pointer(fn)).invoke(); return null;
        case 1: return ((F_J_) WordFactory.pointer(fn)).invoke();
        case 2: return ((F_D_) WordFactory.pointer(fn)).invoke();
        case 3: return ((F_F_) WordFactory.pointer(fn)).invoke();
        case 4: ((F_V_D) WordFactory.pointer(fn)).invoke(dblV(a[0])); return null;
        case 5: return ((F_J_D) WordFactory.pointer(fn)).invoke(dblV(a[0]));
        case 6: return ((F_D_D) WordFactory.pointer(fn)).invoke(dblV(a[0]));
        case 7: return ((F_F_D) WordFactory.pointer(fn)).invoke(dblV(a[0]));
        case 8: ((F_V_F) WordFactory.pointer(fn)).invoke(fltV(a[0])); return null;
        case 9: return ((F_J_F) WordFactory.pointer(fn)).invoke(fltV(a[0]));
        case 10: return ((F_D_F) WordFactory.pointer(fn)).invoke(fltV(a[0]));
        case 11: return ((F_F_F) WordFactory.pointer(fn)).invoke(fltV(a[0]));
        case 12: ((F_V_DD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1])); return null;
        case 13: return ((F_J_DD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]));
        case 14: return ((F_D_DD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]));
        case 15: return ((F_F_DD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]));
        case 16: ((F_V_DF) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1])); return null;
        case 17: return ((F_J_DF) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1]));
        case 18: return ((F_D_DF) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1]));
        case 19: return ((F_F_DF) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1]));
        case 20: ((F_V_FD) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1])); return null;
        case 21: return ((F_J_FD) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1]));
        case 22: return ((F_D_FD) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1]));
        case 23: return ((F_F_FD) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1]));
        case 24: ((F_V_FF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1])); return null;
        case 25: return ((F_J_FF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]));
        case 26: return ((F_D_FF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]));
        case 27: return ((F_F_FF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]));
        case 28: ((F_V_DDD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), dblV(a[2])); return null;
        case 29: return ((F_J_DDD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), dblV(a[2]));
        case 30: return ((F_D_DDD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), dblV(a[2]));
        case 31: return ((F_F_DDD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), dblV(a[2]));
        case 32: ((F_V_DDF) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), fltV(a[2])); return null;
        case 33: return ((F_J_DDF) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), fltV(a[2]));
        case 34: return ((F_D_DDF) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), fltV(a[2]));
        case 35: return ((F_F_DDF) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), fltV(a[2]));
        case 36: ((F_V_DFD) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1]), dblV(a[2])); return null;
        case 37: return ((F_J_DFD) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1]), dblV(a[2]));
        case 38: return ((F_D_DFD) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1]), dblV(a[2]));
        case 39: return ((F_F_DFD) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1]), dblV(a[2]));
        case 40: ((F_V_DFF) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1]), fltV(a[2])); return null;
        case 41: return ((F_J_DFF) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1]), fltV(a[2]));
        case 42: return ((F_D_DFF) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1]), fltV(a[2]));
        case 43: return ((F_F_DFF) WordFactory.pointer(fn)).invoke(dblV(a[0]), fltV(a[1]), fltV(a[2]));
        case 44: ((F_V_FDD) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1]), dblV(a[2])); return null;
        case 45: return ((F_J_FDD) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1]), dblV(a[2]));
        case 46: return ((F_D_FDD) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1]), dblV(a[2]));
        case 47: return ((F_F_FDD) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1]), dblV(a[2]));
        case 48: ((F_V_FDF) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1]), fltV(a[2])); return null;
        case 49: return ((F_J_FDF) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1]), fltV(a[2]));
        case 50: return ((F_D_FDF) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1]), fltV(a[2]));
        case 51: return ((F_F_FDF) WordFactory.pointer(fn)).invoke(fltV(a[0]), dblV(a[1]), fltV(a[2]));
        case 52: ((F_V_FFD) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), dblV(a[2])); return null;
        case 53: return ((F_J_FFD) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), dblV(a[2]));
        case 54: return ((F_D_FFD) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), dblV(a[2]));
        case 55: return ((F_F_FFD) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), dblV(a[2]));
        case 56: ((F_V_FFF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), fltV(a[2])); return null;
        case 57: return ((F_J_FFF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), fltV(a[2]));
        case 58: return ((F_D_FFF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), fltV(a[2]));
        case 59: return ((F_F_FFF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), fltV(a[2]));
        case 60: ((F_V_FFFF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), fltV(a[2]), fltV(a[3])); return null;
        case 61: return ((F_J_FFFF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), fltV(a[2]), fltV(a[3]));
        case 62: return ((F_D_FFFF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), fltV(a[2]), fltV(a[3]));
        case 63: return ((F_F_FFFF) WordFactory.pointer(fn)).invoke(fltV(a[0]), fltV(a[1]), fltV(a[2]), fltV(a[3]));
        case 64: ((F_V_DDDD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), dblV(a[2]), dblV(a[3])); return null;
        case 65: return ((F_J_DDDD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), dblV(a[2]), dblV(a[3]));
        case 66: return ((F_D_DDDD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), dblV(a[2]), dblV(a[3]));
        case 67: return ((F_F_DDDD) WordFactory.pointer(fn)).invoke(dblV(a[0]), dblV(a[1]), dblV(a[2]), dblV(a[3]));
        case 68: ((F_V_J) WordFactory.pointer(fn)).invoke(longV(a[0])); return null;
        case 69: return ((F_J_J) WordFactory.pointer(fn)).invoke(longV(a[0]));
        case 70: return ((F_D_J) WordFactory.pointer(fn)).invoke(longV(a[0]));
        case 71: return ((F_F_J) WordFactory.pointer(fn)).invoke(longV(a[0]));
        case 72: ((F_V_JD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1])); return null;
        case 73: return ((F_J_JD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]));
        case 74: return ((F_D_JD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]));
        case 75: return ((F_F_JD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]));
        case 76: ((F_V_JF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1])); return null;
        case 77: return ((F_J_JF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]));
        case 78: return ((F_D_JF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]));
        case 79: return ((F_F_JF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]));
        case 80: ((F_V_JDD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2])); return null;
        case 81: return ((F_J_JDD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]));
        case 82: return ((F_D_JDD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]));
        case 83: return ((F_F_JDD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]));
        case 84: ((F_V_JDF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2])); return null;
        case 85: return ((F_J_JDF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2]));
        case 86: return ((F_D_JDF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2]));
        case 87: return ((F_F_JDF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2]));
        case 88: ((F_V_JFD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2])); return null;
        case 89: return ((F_J_JFD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2]));
        case 90: return ((F_D_JFD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2]));
        case 91: return ((F_F_JFD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2]));
        case 92: ((F_V_JFF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2])); return null;
        case 93: return ((F_J_JFF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]));
        case 94: return ((F_D_JFF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]));
        case 95: return ((F_F_JFF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]));
        case 96: ((F_V_JDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]), dblV(a[3])); return null;
        case 97: return ((F_J_JDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]), dblV(a[3]));
        case 98: return ((F_D_JDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]), dblV(a[3]));
        case 99: return ((F_F_JDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]), dblV(a[3]));
        case 100: ((F_V_JDDF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]), fltV(a[3])); return null;
        case 101: return ((F_J_JDDF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]), fltV(a[3]));
        case 102: return ((F_D_JDDF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]), fltV(a[3]));
        case 103: return ((F_F_JDDF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]), fltV(a[3]));
        case 104: ((F_V_JDFD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2]), dblV(a[3])); return null;
        case 105: return ((F_J_JDFD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2]), dblV(a[3]));
        case 106: return ((F_D_JDFD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2]), dblV(a[3]));
        case 107: return ((F_F_JDFD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2]), dblV(a[3]));
        case 108: ((F_V_JDFF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2]), fltV(a[3])); return null;
        case 109: return ((F_J_JDFF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2]), fltV(a[3]));
        case 110: return ((F_D_JDFF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2]), fltV(a[3]));
        case 111: return ((F_F_JDFF) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), fltV(a[2]), fltV(a[3]));
        case 112: ((F_V_JFDD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2]), dblV(a[3])); return null;
        case 113: return ((F_J_JFDD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2]), dblV(a[3]));
        case 114: return ((F_D_JFDD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2]), dblV(a[3]));
        case 115: return ((F_F_JFDD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2]), dblV(a[3]));
        case 116: ((F_V_JFDF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2]), fltV(a[3])); return null;
        case 117: return ((F_J_JFDF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2]), fltV(a[3]));
        case 118: return ((F_D_JFDF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2]), fltV(a[3]));
        case 119: return ((F_F_JFDF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), dblV(a[2]), fltV(a[3]));
        case 120: ((F_V_JFFD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]), dblV(a[3])); return null;
        case 121: return ((F_J_JFFD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]), dblV(a[3]));
        case 122: return ((F_D_JFFD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]), dblV(a[3]));
        case 123: return ((F_F_JFFD) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]), dblV(a[3]));
        case 124: ((F_V_JFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]), fltV(a[3])); return null;
        case 125: return ((F_J_JFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]), fltV(a[3]));
        case 126: return ((F_D_JFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]), fltV(a[3]));
        case 127: return ((F_F_JFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]), fltV(a[3]));
        case 128: ((F_V_JFFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]), fltV(a[3]), fltV(a[4])); return null;
        case 129: return ((F_J_JFFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]), fltV(a[3]), fltV(a[4]));
        case 130: return ((F_D_JFFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), fltV(a[1]), fltV(a[2]), fltV(a[3]), fltV(a[4]));
        case 131: ((F_V_JDDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]), dblV(a[3]), dblV(a[4])); return null;
        case 132: return ((F_J_JDDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]), dblV(a[3]), dblV(a[4]));
        case 133: return ((F_D_JDDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), dblV(a[1]), dblV(a[2]), dblV(a[3]), dblV(a[4]));
        case 134: ((F_V_JJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1])); return null;
        case 135: return ((F_J_JJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]));
        case 136: return ((F_D_JJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]));
        case 137: return ((F_F_JJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]));
        case 138: ((F_V_JJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2])); return null;
        case 139: return ((F_J_JJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]));
        case 140: return ((F_D_JJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]));
        case 141: return ((F_F_JJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]));
        case 142: ((F_V_JJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2])); return null;
        case 143: return ((F_J_JJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]));
        case 144: return ((F_D_JJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]));
        case 145: return ((F_F_JJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]));
        case 146: ((F_V_JJDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3])); return null;
        case 147: return ((F_J_JJDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]));
        case 148: return ((F_D_JJDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]));
        case 149: return ((F_F_JJDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]));
        case 150: ((F_V_JJDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), fltV(a[3])); return null;
        case 151: return ((F_J_JJDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), fltV(a[3]));
        case 152: return ((F_D_JJDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), fltV(a[3]));
        case 153: return ((F_F_JJDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), fltV(a[3]));
        case 154: ((F_V_JJFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), dblV(a[3])); return null;
        case 155: return ((F_J_JJFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), dblV(a[3]));
        case 156: return ((F_D_JJFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), dblV(a[3]));
        case 157: return ((F_F_JJFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), dblV(a[3]));
        case 158: ((F_V_JJFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3])); return null;
        case 159: return ((F_J_JJFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]));
        case 160: return ((F_D_JJFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]));
        case 161: return ((F_F_JJFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]));
        case 162: ((F_V_JJDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]), dblV(a[4])); return null;
        case 163: return ((F_J_JJDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]), dblV(a[4]));
        case 164: return ((F_D_JJDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]), dblV(a[4]));
        case 165: ((F_V_JJDDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]), fltV(a[4])); return null;
        case 166: return ((F_J_JJDDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]), fltV(a[4]));
        case 167: return ((F_D_JJDDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]), fltV(a[4]));
        case 168: ((F_V_JJDFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), fltV(a[3]), dblV(a[4])); return null;
        case 169: return ((F_J_JJDFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), fltV(a[3]), dblV(a[4]));
        case 170: return ((F_D_JJDFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), fltV(a[3]), dblV(a[4]));
        case 171: ((F_V_JJDFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), fltV(a[3]), fltV(a[4])); return null;
        case 172: return ((F_J_JJDFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), fltV(a[3]), fltV(a[4]));
        case 173: return ((F_D_JJDFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), fltV(a[3]), fltV(a[4]));
        case 174: ((F_V_JJFDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), dblV(a[3]), dblV(a[4])); return null;
        case 175: return ((F_J_JJFDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), dblV(a[3]), dblV(a[4]));
        case 176: return ((F_D_JJFDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), dblV(a[3]), dblV(a[4]));
        case 177: ((F_V_JJFDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), dblV(a[3]), fltV(a[4])); return null;
        case 178: return ((F_J_JJFDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), dblV(a[3]), fltV(a[4]));
        case 179: return ((F_D_JJFDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), dblV(a[3]), fltV(a[4]));
        case 180: ((F_V_JJFFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]), dblV(a[4])); return null;
        case 181: return ((F_J_JJFFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]), dblV(a[4]));
        case 182: return ((F_D_JJFFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]), dblV(a[4]));
        case 183: ((F_V_JJFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]), fltV(a[4])); return null;
        case 184: return ((F_J_JJFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]), fltV(a[4]));
        case 185: return ((F_D_JJFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]), fltV(a[4]));
        case 186: ((F_V_JJFFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]), fltV(a[4]), fltV(a[5])); return null;
        case 187: return ((F_J_JJFFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]), fltV(a[4]), fltV(a[5]));
        case 188: return ((F_D_JJFFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), fltV(a[2]), fltV(a[3]), fltV(a[4]), fltV(a[5]));
        case 189: ((F_V_JJDDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]), dblV(a[4]), dblV(a[5])); return null;
        case 190: return ((F_J_JJDDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]), dblV(a[4]), dblV(a[5]));
        case 191: return ((F_D_JJDDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), dblV(a[2]), dblV(a[3]), dblV(a[4]), dblV(a[5]));
        case 192: ((F_V_JJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2])); return null;
        case 193: return ((F_J_JJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]));
        case 194: return ((F_D_JJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]));
        case 195: return ((F_F_JJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]));
        case 196: ((F_V_JJJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3])); return null;
        case 197: return ((F_J_JJJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]));
        case 198: return ((F_D_JJJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]));
        case 199: return ((F_F_JJJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]));
        case 200: ((F_V_JJJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3])); return null;
        case 201: return ((F_J_JJJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]));
        case 202: return ((F_D_JJJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]));
        case 203: return ((F_F_JJJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]));
        case 204: ((F_V_JJJDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), dblV(a[4])); return null;
        case 205: return ((F_J_JJJDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), dblV(a[4]));
        case 206: return ((F_D_JJJDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), dblV(a[4]));
        case 207: ((F_V_JJJDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), fltV(a[4])); return null;
        case 208: return ((F_J_JJJDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), fltV(a[4]));
        case 209: return ((F_D_JJJDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), fltV(a[4]));
        case 210: ((F_V_JJJFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), dblV(a[4])); return null;
        case 211: return ((F_J_JJJFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), dblV(a[4]));
        case 212: return ((F_D_JJJFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), dblV(a[4]));
        case 213: ((F_V_JJJFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), fltV(a[4])); return null;
        case 214: return ((F_J_JJJFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), fltV(a[4]));
        case 215: return ((F_D_JJJFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), fltV(a[4]));
        case 216: ((F_V_JJJDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), dblV(a[4]), dblV(a[5])); return null;
        case 217: return ((F_J_JJJDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), dblV(a[4]), dblV(a[5]));
        case 218: return ((F_D_JJJDDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), dblV(a[4]), dblV(a[5]));
        case 219: ((F_V_JJJDDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), dblV(a[4]), fltV(a[5])); return null;
        case 220: return ((F_J_JJJDDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), dblV(a[4]), fltV(a[5]));
        case 221: return ((F_D_JJJDDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), dblV(a[4]), fltV(a[5]));
        case 222: ((F_V_JJJDFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), fltV(a[4]), dblV(a[5])); return null;
        case 223: return ((F_J_JJJDFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), fltV(a[4]), dblV(a[5]));
        case 224: return ((F_D_JJJDFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), fltV(a[4]), dblV(a[5]));
        case 225: ((F_V_JJJDFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), fltV(a[4]), fltV(a[5])); return null;
        case 226: return ((F_J_JJJDFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), fltV(a[4]), fltV(a[5]));
        case 227: return ((F_D_JJJDFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), dblV(a[3]), fltV(a[4]), fltV(a[5]));
        case 228: ((F_V_JJJFDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), dblV(a[4]), dblV(a[5])); return null;
        case 229: return ((F_J_JJJFDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), dblV(a[4]), dblV(a[5]));
        case 230: return ((F_D_JJJFDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), dblV(a[4]), dblV(a[5]));
        case 231: ((F_V_JJJFDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), dblV(a[4]), fltV(a[5])); return null;
        case 232: return ((F_J_JJJFDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), dblV(a[4]), fltV(a[5]));
        case 233: return ((F_D_JJJFDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), dblV(a[4]), fltV(a[5]));
        case 234: ((F_V_JJJFFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), fltV(a[4]), dblV(a[5])); return null;
        case 235: return ((F_J_JJJFFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), fltV(a[4]), dblV(a[5]));
        case 236: return ((F_D_JJJFFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), fltV(a[4]), dblV(a[5]));
        case 237: ((F_V_JJJFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), fltV(a[4]), fltV(a[5])); return null;
        case 238: return ((F_J_JJJFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), fltV(a[4]), fltV(a[5]));
        case 239: return ((F_D_JJJFFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), fltV(a[3]), fltV(a[4]), fltV(a[5]));
        case 240: ((F_V_JJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3])); return null;
        case 241: return ((F_J_JJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]));
        case 242: return ((F_D_JJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]));
        case 243: return ((F_F_JJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]));
        case 244: ((F_V_JJJJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), dblV(a[4])); return null;
        case 245: return ((F_J_JJJJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), dblV(a[4]));
        case 246: return ((F_D_JJJJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), dblV(a[4]));
        case 247: ((F_V_JJJJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), fltV(a[4])); return null;
        case 248: return ((F_J_JJJJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), fltV(a[4]));
        case 249: return ((F_D_JJJJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), fltV(a[4]));
        case 250: ((F_V_JJJJDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), dblV(a[4]), dblV(a[5])); return null;
        case 251: return ((F_J_JJJJDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), dblV(a[4]), dblV(a[5]));
        case 252: return ((F_D_JJJJDD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), dblV(a[4]), dblV(a[5]));
        case 253: ((F_V_JJJJDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), dblV(a[4]), fltV(a[5])); return null;
        case 254: return ((F_J_JJJJDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), dblV(a[4]), fltV(a[5]));
        case 255: return ((F_D_JJJJDF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), dblV(a[4]), fltV(a[5]));
        case 256: ((F_V_JJJJFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), fltV(a[4]), dblV(a[5])); return null;
        case 257: return ((F_J_JJJJFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), fltV(a[4]), dblV(a[5]));
        case 258: return ((F_D_JJJJFD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), fltV(a[4]), dblV(a[5]));
        case 259: ((F_V_JJJJFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), fltV(a[4]), fltV(a[5])); return null;
        case 260: return ((F_J_JJJJFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), fltV(a[4]), fltV(a[5]));
        case 261: return ((F_D_JJJJFF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), fltV(a[4]), fltV(a[5]));
        case 262: ((F_V_JJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4])); return null;
        case 263: return ((F_J_JJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]));
        case 264: return ((F_D_JJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]));
        case 265: ((F_V_JJJJJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), dblV(a[5])); return null;
        case 266: return ((F_J_JJJJJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), dblV(a[5]));
        case 267: return ((F_D_JJJJJD) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), dblV(a[5]));
        case 268: ((F_V_JJJJJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), fltV(a[5])); return null;
        case 269: return ((F_J_JJJJJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), fltV(a[5]));
        case 270: return ((F_D_JJJJJF) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), fltV(a[5]));
        case 271: ((F_V_JJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5])); return null;
        case 272: return ((F_J_JJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]));
        case 273: return ((F_D_JJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]));
        case 274: ((F_V_JJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6])); return null;
        case 275: return ((F_J_JJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6]));
        case 276: return ((F_D_JJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6]));
        case 277: ((F_V_JJJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6]), longV(a[7])); return null;
        case 278: return ((F_J_JJJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6]), longV(a[7]));
        case 279: return ((F_D_JJJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6]), longV(a[7]));
        case 280: ((F_V_JJJJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6]), longV(a[7]), longV(a[8])); return null;
        case 281: return ((F_J_JJJJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6]), longV(a[7]), longV(a[8]));
        case 282: return ((F_D_JJJJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6]), longV(a[7]), longV(a[8]));
        case 283: ((F_V_JJJJJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6]), longV(a[7]), longV(a[8]), longV(a[9])); return null;
        case 284: return ((F_J_JJJJJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6]), longV(a[7]), longV(a[8]), longV(a[9]));
        case 285: return ((F_D_JJJJJJJJJJ) WordFactory.pointer(fn)).invoke(longV(a[0]), longV(a[1]), longV(a[2]), longV(a[3]), longV(a[4]), longV(a[5]), longV(a[6]), longV(a[7]), longV(a[8]), longV(a[9]));
        }
        throw new IllegalArgumentException("bad shape id: " + id);
    }
}
